name: LADS
channels:
- pytorch
- defaults
dependencies:
- pytorch=1.12.1
- pip=21.0.1
- torchvision==0.13.1
- pandas==1.2.3
- numpy=1.19.2
- scipy==1.6.1
- seaborn==0.11.1
- dill==0.3.3
- tqdm==4.49.0
- jupyter=1.0.0
- jupyter_client=6.1.7
- jupyter_console=6.2.0
- jupyter_core=4.7.1
- jupyterlab_pygments=0.1.2
- jupyterlab_widgets=1.0.0
- pillow=8.1.1
- pip:
    - tensorboardx==1.8
    - robustness
    - omegaconf
    - wandb
    - cox
    - ftfy
    - regex
    - tensorflow-gpu
    - tensorflow_hub
    - statsmodels
    - clip
    - snorkel
    - pytorch_adapt
    - transformers
    - pytorch_revgrad
    - open_clip
