EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "LADS_GroZi"
  SEED: 0
  TEXT_PROMPTS: ['a blurry photo of {}.']
  # NEUTRAL_TEXT_PROMPTS: [['a blurry photo of {}.', 'a photo of {} in the grocery store.', 'a video of {}.']]
  NEUTRAL_TEXT_PROMPTS: ['a stock photo of {}.']
  AUGMENTATION: 'Directional'
  EPOCHS: 200
  LOG_HIST: True
  ENSAMBLE: True
  
  
DATA:
  DATASET: "GroZi"
  LOAD_CACHED: True
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    WEIGHT_DECAY: 0.05
    CHECKPOINT: 'checkpoint/mlp_simple.pth'
    CHECKPOINT_NAME: 'GroZi/mlp-directional'
    RESUME: False
  USE_DOM_GT: True

AUGMENTATION:
  MODEL:
    LR: 0.001
    WEIGHT_DECAY: 0.05
    NUM_LAYERS: 2
  GENERIC: False
  DOM_LABELS: ['inSitu']