EXP:
  ADVICE_METHOD: "CLIPZS"
  WANDB_SILENT: False
  PROJ: "DomainNetMini_LADS_Replication"
  SEED: 0
  TEXT_PROMPTS: []
  TEMPLATES: 'domainnet_mini_templates'
  
DATA:
  DATASET: "DomainNetMini"
  BATCH_SIZE: 64
  # LOAD_CACHED: False
  UPWEIGHT_CLASSES: True
  # SAVE_PATH: "data/DomainNetMini/save.pth"

METHOD:
  MODEL:
    NUM_LAYERS: 1
    SEPERATE_CLASSES: True
    RESUME: True
  NORMALIZE: True