EXP:
  ADVICE_METHOD: "Base"
  WANDB_SILENT: False
  PROJ: "LADS"
  SEED: 0
  TEXT_PROMPTS: ["a photo of a {}."]
  NEUTRAL_TEXT_PROMPTS: []
  TEMPLATES: "no_template"
  CHECKPOINT_VAL: True
  LOG_NN: True
  CLIP_MODEL: 'ViT-L/14'
  IMAGE_FEATURES: 'clip'
  AUGMENTATION: None
  ENSAMBLE: False
  CLIP_PRETRAINED_DATASET: 'openai'
  DEBUG: False

DATA:
  DATASET: "Waterbirds95"
  BATCH_SIZE: 256
  LOAD_CACHED: True
  SAVE_PATH: 'embeddings'
  UPWEIGHT_DOMAINS: False
  UPWEIGHT_CLASSES: True
  MODEL_DIM: 1024

METHOD:
  MODEL:
    WEAK_LABELS: False 
    NUM_LAYERS: 1
    LR: 0.001
    SEPERATE_CLASSES: True
    RESUME: False
    CHECKPOINT: './checkpoint/mlp_test.sav'
    CHECKPOINT_NAME: 'ColoredMNISTSimple/mlp'
    WEIGHT_DECAY: 0.05
    HIDDEN_DIM: 384
    ARCH: MLP
  NORMALIZE: True
  USE_DOM_GT: False
  NORMALIZE_OUTPUT: True

AUGMENTATION:
  MODEL:
    LR: 0.005
    WEIGHT_DECAY: 0.05
    HIDDEN_DIM: 384
    NUM_LAYERS: 1
    ARCH: MLP
  LOSS_TYPE: 'cosine'
  EPOCHS: 50
  GENERIC: False
  ALPHA: 0.5
  INCLUDE_ORIG_TRAINING: True
  TEST_TIME_AUG: False
  CLIP_NN_LOSS: False
  NN_CLASS_SPECIFIC: False
  COMPARE_BEFORE_AUG: True
  NN_INCLUDE_SAMPLE: True
  DOM_WEIGHT: 1.0
  DOM_SPECIFIC_XE: False
  DOM_LABELS: []
  NN_WEIGHT: 0.0
  REG_WEIGHT: 0.1