EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "Waterbirds_ViT14"
  SEED: 0
  TEXT_PROMPTS: ['a photo of a {} on forest.', 'a photo of a {} on water.']
  NEUTRAL_TEXT_PROMPTS: ['a photo of a {}.']
  EPOCHS: 200

DATA:
  DATASET: "Waterbirds"
  BATCH_SIZE: 256
  LOAD_CACHED: True

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    # LR: 0.005
    # WEIGHT_DECAY: 0.005
    CHECKPOINT: 'checkpoint/mlp.pth'
    CHECKPOINT_NAME: "mlp"
    RESUME: False
  USE_DOM_GT: True